repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    - id: black
      args: [--line-length=125, --skip-string-normalization]
      language_version: python3.13